# Generated by Django 4.0.6 on 2022-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetriCubiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_de_metri_cubi', models.CharField(max_length=100)),
            ],
        ),
    ]
