# Generated by Django 4.0.6 on 2022-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparsinginspectorulpadurii', '0002_okmetricubi'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotOkMetriCubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_inmatriculare', models.CharField(max_length=100)),
                ('volum_detectat', models.CharField(max_length=100)),
                ('volum_avizat', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
