# Generated by Django 4.0.6 on 2022-09-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webparsinginspectorulpadurii', '0003_notokmetricubi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OkMetriCubi',
            new_name='IstoricMetriCubi',
        ),
    ]
