# Generated by Django 4.0.6 on 2022-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparsinginspectorulpadurii', '0004_rename_okmetricubi_istoricmetricubi'),
    ]

    operations = [
        migrations.AddField(
            model_name='istoricmetricubi',
            name='day',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='istoricmetricubi',
            name='hour',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='istoricmetricubi',
            name='minute',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='istoricmetricubi',
            name='month',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='istoricmetricubi',
            name='second',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='istoricmetricubi',
            name='year',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
