# Generated by Django 4.0.6 on 2022-09-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparsinginspectorulpadurii', '0005_istoricmetricubi_day_istoricmetricubi_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='day',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='hour',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='minute',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='month',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='second',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='year',
            field=models.CharField(default='.', max_length=100),
        ),
    ]
