# Generated by Django 4.0.6 on 2022-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webparsinginspectorulpadurii', '0007_remove_istoricmetricubi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='istoricmetricubi',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='hour',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='minute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='month',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='second',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='istoricmetricubi',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
