# Generated by Django 4.0.6 on 2022-09-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webparsinginspectorulpadurii', '0008_istoricmetricubi_date_alter_istoricmetricubi_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istoricmetricubi',
            name='day',
        ),
        migrations.RemoveField(
            model_name='istoricmetricubi',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='istoricmetricubi',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='istoricmetricubi',
            name='month',
        ),
        migrations.RemoveField(
            model_name='istoricmetricubi',
            name='second',
        ),
        migrations.RemoveField(
            model_name='istoricmetricubi',
            name='year',
        ),
    ]
