# Generated by Django 4.0.6 on 2022-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialreader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressComModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_number', models.CharField(max_length=100)),
            ],
        ),
    ]
